config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :motorcycles do 
  	resources :bookings, only: [:new, :create, :show] do
 		resources :reviews, only: [:new, :create]	
  	end
  end
  
  resources :bookings, only: [:index]

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :motorcycle
  belongs_to :user

  has_many :reviews, dependent: :destroy

  validates :motorcycle, :user, :start_date, :end_date, presence:true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def self.user_bookings(user)
  	Booking.where(user: user)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.user_bookings(current_user)

  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @motorcycle = Motorcycle.find(params[:motorcycle_id])
    @booking = Booking.new

    @booking_map = Booking.where.not(latitude: nil, longitude: nil)

    @markers = @booking_map.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
      }
    end
  end

  def create
    @booking = Booking.new(booking_params)

    @booking.motorcycle = Motorcycle.find(params[:motorcycle_id])
    @booking.user = current_user

    if @booking.save
      redirect_to motorcycle_booking_path(@booking.motorcycle, @booking)
    else
      render :new
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :motorcycle_id, :user_id, :address)
  end
end

app/views/bookings/index.html.erb
<h2>All my bookings</h2>

<% @current_user %>

<% @bookings.each do |booking| %>
  <h3><%= link_to booking.motorcycle.name, motorcycle_booking_path(booking.motorcycle, booking) %></h3>
  <h4><%= "from " + booking.start_date.to_s %></h4>
  <h4><%= "to " + booking.end_date.to_s %></h4>
  <br>
<% end %>

app/views/bookings/new.html.erb
<div class="container padded-top">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for [@motorcycle, @booking] do |f| %>
        <%= f.input :address %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit "request booking", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

  <div class="child_1" id="map" style="width: 100%; height: 600px" data-markers="<%= @markers.to_json %>">
  </div>

  <div class="child_2">
    <%= simple_form_for [@motorcycle, @booking] do |f| %>
      <%= f.input :address %>
      <%= f.submit "Enter delivery address", class: "btn btn-primary" %>
    <% end %>
    <br>
    <%= simple_form_for [@motorcycle, @booking] do |f| %>
      <%= f.submit "Confirm location and book motorcycle", class: "btn btn-primary" %>
    <% end %>
  </div>

  <%= javascript_tag do %>

  document.addEventListener("DOMContentLoaded",function(event) {

  var url = new URL(window.location.href);
  var start = url.searchParams.get("token_start");
  var end = url.searchParams.get("token_end");
  var start_input = document.getElementById("start_date");
  console.log(start_input);
  var end_input = document.getElementById("end_date");
  start_input._flatpickr.setDate(start,true, "Y-m-d");
  end_input._flatpickr.setDate(end,true, "Y-m-d");


});




  <% end %>

app/views/bookings/show.html.erb
<div class="booking-status">
	<div class="booking-status-content">
	  <video width="100vw" src="https://res.cloudinary.com/cris7cris/video/upload/v1541247453/iRideNairobi/Roberto.mp4" type="video/mp4" autoplay loop>
      </video>
    	<div class="booking-status-overlay">
    	  <h4> Enjoy your ride <%= @booking.user.email.split('@').first.capitalize %>! </h4>
    	  <p> You've just booked <%= @booking.motorcycle.name %> from <%= @booking.start_date %> to <%= @booking.end_date %></p>
          <p><%= link_to "Add a Review", new_motorcycle_booking_review_path(@booking.motorcycle, @booking) %></p>
          <p><%= link_to "See all your bookings", bookings_path %></p>
    	</div>
    </div>
</div>