config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :motorcycles do 
  	resources :bookings, only: [:new, :create, :show] do
 		resources :reviews, only: [:new, :create]	
  	end
  end
  
  resources :bookings, only: [:index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

  <span style="font-size: 48px;">
    <i class="fas fa-motorcycle"></i>
  </span>
<% end %>

<%= simple_form_for :search, :url => motorcycles_path, method: "get",
  wrapper: :inline_form,
  html: { class: "form-inline" },
  wrapper_mappings: {
    boolean: :inline_boolean
  } do |f| %>

  <%= f.input :starts_at, as: :string, required: false, input_html: {id: "start_date", class: "mr-sm-2"} %>
  <%= f.input :ends_at, as: :string, required: false, input_html: {id: "end_date", class: "mr-sm-2"} %>

  <%= f.button :submit, value="BOOK NOW", class: "btn-primary mx-sm-2" %>
<% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "profile.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>  <div class="link-nav-drop">
              <%= link_to "bookings" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "All my bookings") %>
              <% end %>
              </div>
            </li>
            <li>  <div class="link-nav-drop">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>