config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :motorcycles do 
  	resources :bookings, only: [:new, :create, :show] do
 		resources :reviews, only: [:new, :create]	
  	end
  end
  
  resources :bookings, only: [:index]

end

app/models/motorcycle.rb
class Motorcycle < ApplicationRecord

  has_many :bookings, :dependent => :destroy
  has_many :reviews, through: :bookings
  mount_uploader :uploaded_photo, UploadedPhotoUploader

  validates :name, :motor_type, :description, :price, presence: true


end

app/controllers/motorcycles_controller.rb
class MotorcyclesController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

	def index

    if params["search"]["starts_at"].present? && params["search"]["ends_at"].present?
    # cookies[:start_date] = params["search"]["starts_at"]
    # cookies[:end_date] = params["search"]["ends_at"]

      @motorcycles = []

      a = Date.parse(params["search"]["starts_at"])
      b = Date.parse(params["search"]["ends_at"])

      Motorcycle.all.each do |motorcycle|

        motorcycle.bookings.each do |booking|
          c = booking.start_date
          d = booking.end_date

          if !(a..b).overlaps?(c..d)
            @motorcycles << booking.motorcycle
          end

          # if ((booking.start_date > Date.parse(params["search"]["ends_at"]) ||
          #   booking.end_date < Date.parse(params["search"]["starts_at"])) &&
          #   Date.parse(params["starts_at"]) < Date.parse(params["ends_at"])
        end
      end
      @motorcycles
    else
      @motorcycles = Motorcycle.all
    end
  end

	def show
	  @motorcycle = Motorcycle.find(params[:id])
	end

	def new
      @motorcycle = Motorcycle.new
  end

    def create
      @motorcycle = Motorcycle.new(motorcycle_params)
      @motorcycle.save

      redirect_to @motorcycle
    end

	def edit
      @motorcycle = Motorcycle.find(params[:id])
  end

  def update
      @motorcycle = Motorcycle.find(params[:id])
      @motorcycle.update(motorcycle_params)
      redirect_to motorcycle_path(@motorcycle)
  end

  def destroy
    @motorcycle = Motorcycle.find(params[:id])
    @motorcycle.destroy

    redirect_to @motorcycles
  end

private

  def motorcycle_params
    params.require(:motorcycle).permit(:name, :motor_type, :description, :price, :picture, :uploaded_photo)
  end

end

app/views/motorcycles/edit.html.erb
<h2>Edit the motorcycle</h2>

<%= simple_form_for @motorcycle do |f| %>
  <%= f.input :name, label: 'Name' %>
  <%= f.input :motor_type, label: 'Type' %>
  <%= f.input :description, label: 'Description' %>
  <%= f.input :price, label: 'Price' %>
  <%= f.input :uploaded_photo %>
  <%= f.input :uploaded_photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/motorcycles/index.html.erb
<div class="moto-wrapper">
  <div class="row">
   <% @motorcycles.each do |moto|%>

    <div class="col-xs-12 col-sm-4">
    	
		<div class="card"  style="background-image: linear-gradient(rgba(232, 224, 224, 0.3), rgba(196, 55, 16, 0.2)), url(<%= cl_image_path(moto.picture)%>);">


	    	<div class="card-category"><h4><%= link_to moto.name, motorcycle_path(moto, search: {starts_at: params["search"]["starts_at"], ends_at: params["search"]["ends_at"]} ) %></h4></div>
	        <div class="card-description">
	      <!-- insert <div class="card"> -->
	      		<p><%= moto.motor_type  %></p>
	         	<p><%= moto.price.to_s + "USD per day" %></p>
	         	<p><%= link_to "Edit ", edit_motorcycle_path(moto) %><%= link_to "Delete", moto, method: :delete, data: { confirm: "Are you sure you want to delete this motorcycle?" } %></p>
	         	<p></p>
	        </div>

	    </div>

    </div>

   <% end %>
  </div>
</div>

app/views/motorcycles/new.html.erb
<h2>Create a new motorcyle</h2>

<%= simple_form_for @motorcycle do |f| %>
  <%= f.input :name, label: 'Name' %>
  <%= f.input :motor_type, label: 'Type' %>
  <%= f.input :description, label: 'Description' %>
  <%= f.input :price, label: 'Price' %>
  <%= f.input :uploaded_photo %>
  <%= f.input :uploaded_photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/motorcycles/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-md-6">
      <div id="motorcycle-image">
        <% if @motorcycle.uploaded_photo.present? %>
          <%= cl_image_tag(@motorcycle.uploaded_photo) %>
        <% else %>
          <%= image_tag(@motorcycle.picture) %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row-fluid">
        <button id="book-moto-btn">
          <% if user_signed_in? %>
            <div id="href-btn">
              <%= link_to "Book #{@motorcycle.name} now", new_motorcycle_booking_path(@motorcycle, search: {starts_at: params["search"]["starts_at"], ends_at: params["search"]["ends_at"]}) %>
            </div>
          <% else %>
              <%= link_to "Book #{@motorcycle.name} now", new_user_registration_path(moto: params[:id], search: {starts_at: params["search"]["starts_at"], ends_at: params["search"]["ends_at"]}) %>
          <% end %>
        </button>
      </div>
      <div class="row-fluid">
          <br>
          <p><%= @motorcycle.motor_type  %></p>
          <br>
          <p><%= @motorcycle.description  %></p>
          <br>
          <p style="font-weight:bold" align="center" id="big-font"><%= @motorcycle.price.to_s + " USD per day" %></p>
      </div>
      <div class="row-fluid">
         <div class="card">
            <p>
              <%= pluralize @motorcycle.reviews.size, "review" %>
            </p>
            <br>
            <% @motorcycle.reviews.each do |review|%>
              <% review.stars.times do%>
                <i class="far fa-star"></i>
              <% end %>
              <br>
              <p><%= review.content %></p>
              <br>
            <% end %>
          </div>
      </div>

    </div>
  </div>


</div>
>>>>>>> 7f9dada931bfbc6be24b325572f0d5b3cfbe4087